apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/2143-Labs/timestone-argo.git
    targetRevision: talos-cutover
    path: base/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jqPathExpressions:
        - .status
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .status
